name: Build and Deploy ChaikaLanding image

on:
  push:
    branches:
      - master
      - CHL-*
      - CHOPS-*
      - fix/*

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.JS
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  version:
    name: Checkout code and check ver
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version_modified: ${{ steps.check-version.outputs.version_modified }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check if version was modified
        id: check-version
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "VERSION"; then
              echo "version_modified=true" >> $GITHUB_OUTPUT
          else
              echo "version_modified=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Push new image into registry
    runs-on: ubuntu-latest
    needs: version
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.checkout.outputs.version_modified == 'true' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.remystorage.ru
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d ' \n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            harbor.remystorage.ru/chaika/chaika-landing:${{ steps.version.outputs.version }}
            harbor.remystorage.ru/chaika/chaika-landing:latest
          file: ./Dockerfile
